### ISSUE TITLE
Polling for service creation proceeds even if creation failed

### ISSUE THREAD

**Issue by nedgar** [chris-anchez/conversation-with-discovery-openwhisk#3]
If creation of the `discovery-for-demo` service fails, e.g. due to hitting limit for # services, the polling for service creation still continues (though it looks like it tries to check creation message).
As a result, the deployment job runs for ~60 mins before timing out.

![image](https://user-images.githubusercontent.com/692834/30973363-e927568a-a43a-11e7-92b8-e4a30c33a913.png)

See event in Amplitude: https://analytics.amplitude.com/org/10809/project/164470/search/32067388480?sessionHandle=-B_V7AS9oD_d3XYRA_oJ2_%255BOTC%2520server%255D%2520uid%2520ea55efd9-95d9-4553-ac4e-731252c6b82c&eventId=222d9bbe-a38d-11e7-91c4-023ad108511a

**Comment by nedgar** [comment]
End of log:

![image](https://user-images.githubusercontent.com/692834/30973592-7fbde0aa-a43b-11e7-85e3-2fa3ed4234a8.png)

**Comment by nedgar** [comment]
FYI @cvsanchez42

**Comment by germanattanasio** [comment]
Hi @nedgar, we are thinking of removing the deploy to bluemix for a new experience we are working on. Stay tune!

**Comment by mamoonraja** [comment]
We are not providing the option to `Deploy to Bluemix` in this demo anymore.
