### ISSUE TITLE
Failed during npm run train

### ISSUE THREAD

**Issue by jeff-barnes** [chris-anchez/conversation-with-discovery-openwhisk#40]
Got the attached error when running npm run train
Can anybody help?
[2018-03-23T15_58_44_318Z-debug.log](https://github.com/watson-developer-cloud/assistant-with-discovery-openwhisk/files/1842441/2018-03-23T15_58_44_318Z-debug.log)

**Comment by germanattanasio** [comment]
The `train` command does 
```
cp .env.example .env && node ./train-conversation.js && node ./train-discovery.js
```

You need to rename the `.env.example` to be `.env` and run
```
node ./train-conversation.js
```
and
```
node ./train-discovery.js
```

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
