### ISSUE TITLE
Failed during sh create-openwhisk-actions.sh

### ISSUE THREAD

**Issue by JotaRaffalli** [chris-anchez/conversation-with-discovery-openwhisk#41]
Hi, got this error while running  `sh create-openwhisk-actions.sh `
`create-openwhisk-actions.sh: line 1: source: .env: file not found`
I do have an env file  generated in the instructions before.

**Comment by germanattanasio** [comment]
Are you running Windows? Mac? What are the steps you followed to get to that error message?

**Comment by JotaRaffalli** [comment]
Hello @germanattanasio! 
I added a `./` before the **.env** in shell script and it worked. 
create-openwhisk-actions.sh `source ./.env; `
Using Windows 10.
Cheers! 👍

**Comment by germanattanasio** [comment]
@JotaRaffalli do you mind creating a Pull Request with your fix? I think it will help others.

**Comment by JotaRaffalli** [comment]
Sure thing!
