### ISSUE TITLE
What tool did you use to pull web pages into json documents? 

### ISSUE THREAD

**Issue by LTepliakov** [chris-anchez/conversation-with-discovery-openwhisk#63]
Hello Team.
Can you please share how did you pull the web pages from car support site into json documents that you place into Watson Discovery Collection?

Did you use some tool for that, or did it manually?

**Comment by germanattanasio** [comment]
Hi @LTepliakov we didn't pull the data from web pages. We did it manually

**Comment by LTepliakov** [comment]
Thank you German
