### ISSUE TITLE
No response from Watson, just one-way communication?

### ISSUE THREAD

**Issue by ghost** [chris-anchez/conversation-with-discovery-openwhisk#9]
Completed all instructions as outlined with no complying issues, the only substitute was using the new OpenWhisk replacement service, Cloud Functions.  You can test my app here, https://watsonnradvisorconversationapp.mybluemix.net/ to verify issue.  Any ideas on where to start looking for the break would be appreciated, thanks!

**Comment by anweshan** [comment]
Hi! Thanks for letting us know. We are looking into this. 

When you go to Cloud Functions -> APIs -> the API you made, make sure under definition 'Require applications to authenticate via API key' is false -- this is something that we are working on changing in an upcoming release. Also, the sharing tab has a link to an API portal which you can test requests, to see if you are able to get a valid response from the OpenWhisk API sequence.

**Comment by ghost** [comment]
@anweshan, thank you for this information.  I did change the 'Require applications to authenticate via API key' to false, and I was able to get valid responses from the API portal tests.  However the application still had no response to questions, so I proceeded to revisit the instructions 1-by-1 and found that in the section labeled "Setting up the OpenWhisk Back-end" #4 has an error in the path parameter.  The path is "action" versus "actions", and I corrected this originally to "actions", but is the folder mislabeled as per your java code paths, and should it be "action"?  Or does this really matter?

**Comment by anweshan** [comment]
Thanks for the input, the folder should be called 'actions', that was a mistake in the README in the instructions. As for the no response to questions, we are working on debugging this now.

**Comment by ghost** [comment]
So now that I have followed all the instructions again from scratch, I get the following error when testing the Cloud Functions API:
{
  "name": "AssertionError",
  "expected": true,
  "operator": "==",
  "message": "params.input cannot be null",
  "generatedMessage": false
}
Thoughts?

**Comment by anweshan** [comment]
Did you specify an input?

And yes we are getting the same error - we hope to patch this starter kit by end of today.

**Comment by ghost** [comment]
Not sure, I am new to curl; I used this example request from the API portal (only API address removed):

curl --request POST \
  --url https://service.us.apiconnect.ibmcloud.com/gws/apigateway/api/{my private API address}/conversation-with-discovery/submit \
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --data '{"id":8377822884134912}'

I greatly appreciate your prompt responses, and I look forward to your patch!

**Comment by anweshan** [comment]
Hi, I think this issue is fixed with the PR I just posted https://github.com/watson-developer-cloud/conversation-with-discovery-openwhisk/pull/12

It changes the instructions to create the API -- delete your API & sequence, make a new sequence and see if this fixes the problem
